name: Deploy Node.js app to Production

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Ssh to server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        script: |
          cd /root/test-app || exit

          # Reset any local changes
          git reset --hard HEAD
          git clean -fd

          # Pull the latest changes from the main branch
          git pull origin main

          npm install
          pm2 restart test-app || pm2 start ./src/index.js --name test-app
          if [ $? -eq 0 ]; then
            echo "Deployment successful"
          else
            echo "Deployment failed, rolling back to previous version"
            git reflog | grep HEAD@{1} | awk '{print $1}' | xargs git reset --hard
            npm install
            npm start
            exit 1
          }